apiVersion: v1
kind: Service
metadata:
  name: mongo-configservers
  labels:
    app: mongo-configservers
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: NoSQL 数据库
spec:
  ports:
    - name: mongo-configservers
      port: 27019
  clusterIP: None
  selector:
    app: mongo-configservers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-configservers
  labels:
    app: mongo-configservers
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: NoSQL 数据库
spec:
  serviceName: mongo-configservers
  replicas: 3
  selector:
    matchLabels:
      app: mongo-configservers
  template:
    metadata:
      labels:
        app: mongo-configservers
    spec:
      containers:
        - name: mongo
          image: /mongo:4.4.13
          readinessProbe:
            tcpSocket:
              port: 27019
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 27019
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 8
              memory: 32Gi
          command:
            - mongo
            - "--replSet"
            - configserver
            - "--bind_ip"
            - 0.0.0.0
            - "--configsvr"
            - true
#            - --clusterAuthMode
#            - keyFile
#            - --keyFile
#            - /data/mongo-keyfile
          ports:
            - name: mongo-configservers
              containerPort: 27019
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 123456
            - name: MONGO_INITDB_DATABASE
              value: template
          volumeMounts:
            - name: mongo-configservers
              mountPath: /data
          imagePullPolicy: Always
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mongo-configservers
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem