apiVersion: v1
kind: Secret
metadata:
  name: mysql
stringData:
  rootUser: root
  rootHost: '%'
  rootPassword: 123456
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql
spec:
  secretName: mysql
  imageRepository: 
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 3
    podSpec:
      containers:
        - name: router
          livenessProbe:
            httpGet:
              path: /api/20190715/swagger.json
              port: http
              scheme: HTTPS
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/mysqlrouter/mysqlrouter.conf
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  mycnf: |
    [mysqld]
    authentication_policy=mysql_native_password
    skip_name_resolve=1
    explicit_defaults_for_timestamp=1
    user=mysql
    explicit_defaults_for_timestamp
    max_allowed_packet=32M
    bind-address=0.0.0.0
    character-set-server=UTF8MB4
    collation-server=utf8mb4_unicode_ci
    lower_case_table_names=1
    wait_timeout=86400
    default-time_zone='+8:00'
    interactive_timeout=7200
    max_connections=100000
    sync_binlog=1
    relay_log_recovery=1
    log_timestamps=system
    innodb_log_file_size=128M
    innodb_buffer_pool_size=12G
    innodb_buffer_pool_instances=16
    innodb_data_file_path=ibdata1:1024M:autoextend
    innodb_flush_log_at_trx_commit=2
    innodb_log_buffer_size=16M
    innodb_log_file_size=1024M
    innodb_log_files_in_group=4
    innodb_max_dirty_pages_pct=75
    innodb_file_per_table=1
    innodb_io_capacity=2000
    innodb_io_capacity_max=8000
    transaction_isolation=READ-COMMITTED
    innodb_flush_method=O_DIRECT
    innodb_thread_concurrency= 0
    innodb_print_all_deadlocks=on
    innodb_deadlock_detect=on
    innodb_lock_wait_timeout=30
    innodb_parallel_read_threads=4
    information_schema_stats_expiry=1800
