apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api
subjects:
  - kind: ServiceAccount
    name: api
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io