apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
data:
  UMASK: "0660"
  UMASK_DIR: "0750"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-my-cnf
data:
  config: |
    [mysqld]
    innodb_use_native_aio=OFF
    explicit_defaults_for_timestamp=1
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    character-set-server=UTF8MB4
    collation-server=utf8mb4_unicode_ci
    lower_case_table_names=1
    wait_timeout=86400
    default-time_zone='+8:00'
    interactive_timeout=7200
    max_connections=100000
    relay_log_recovery=1
    innodb_autoinc_lock_mode=2
    max_allowed_packet=32M
    binlog_format=row
    
    [client]
    protocol=tcp
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: Z2VvdmlzQDEyMw==
  root-password: Z2VvdmlzQDEyMw==