apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: mariadb-operator
  name: mariadb-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-controller-manager
  namespace: mariadb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb-leader-election-role
  namespace: mariadb-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mariadb-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - backups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - backups/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - backups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - connections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - connections
      - restores
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - connections/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - connections/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - databases/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - grants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - grants/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - grants/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - mariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - mariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - mariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - restores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - restores/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - restores/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - sqljobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - sqljobs/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - sqljobs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - users
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - users/finalizers
    verbs:
      - update
  - apiGroups:
      - mariadb.mmontes.io
    resources:
      - users/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-leader-election-rolebinding
  namespace: mariadb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-leader-election-role
subjects:
  - kind: ServiceAccount
    name: mariadb-controller-manager
    namespace: mariadb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadb-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadb-manager-role
subjects:
  - kind: ServiceAccount
    name: mariadb-controller-manager
    namespace: mariadb-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
  labels:
    app: mariadb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-operator
  template:
    metadata:
      labels:
        app: mariadb-operator
    spec:
      serviceAccountName: mariadb-controller-manager
      terminationGracePeriodSeconds: 10
      containers:
        - image: /mariadb-operator:0.0.15
          name: controller
          args:
            - --metrics-addr=:8080
            - --log-level=INFO
            - --service-monitor-reconciler
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          env:
            - name: CLUSTER_NAME
              value: cluster.local
#          resources:
#            requests:
#              cpu: 10m
#              memory: 32Mi
#            limits:
#              cpu: 100m
#              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-operator-metrics
  namespace: mariadb-operator
  labels:
    app: mariadb-operator
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    app: mariadb-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
  labels:
    app: mariadb-operator
spec:
  selector:
    matchLabels:
      app: mariadb-operator
  endpoints:
    - port: metrics
      interval: 1m