apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: /redis:6.2.7-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig:
      - "appendonly yes"
      - "protected-mode no"
  redis:
    replicas: 3
    image: /redis:6.2.7-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      readOnlyRootFilesystem: false
    customConfig:
      - "appendonly yes"
      - "protected-mode no"
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-keep-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
