apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    app.kubernetes.io/name: elasticsearch
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 搜索引擎服务
spec:
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 搜索引擎服务
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: elasticsearch
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: fix-permissions
          image: /busybox:1.35.0
          command: ['/bin/sh', '-c']
          args:
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map-count
          image: /busybox:1.35.0
          command: ['/bin/sh', '-c']
          args:
            - sysctl -w vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-ulimits
          image: /busybox:1.35.0
          command: ['/bin/sh', '-c']
          args:
            - ulimit -n 65536
      containers:
        - name: elasticsearch
          image: /elasticsearch:7.10.1
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: '4'
              memory: 16Gi
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: cluster.name
              value: elasticsearch
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
            - name: ES_JAVA_OPTS
              value: "-Xms8g -Xmx8g"
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "*"
          volumeMounts:
            - name: elasticsearch
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: elasticsearch
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem