kind: Service
apiVersion: v1
metadata:
  name: emx
  labels:
    app: emx
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-18083
      protocol: TCP
      port: 18083
      targetPort: 18083
      nodePort: 23938
    - name: http-1883
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 50159
  selector:
    app: emqx
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: emqx
  labels:
    app: emqx
  annotations:
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: 'emqx/emqx:4.4.3'
          ports:
            - name: tcp-18083
              containerPort: 18083
              protocol: TCP
            - name: tcp-1883
              containerPort: 1883
              protocol: TCP
            - name: tcp-8081
              containerPort: 8081
              protocol: TCP
            - name: tcp-8083
              containerPort: 8083
              protocol: TCP
            - name: tcp-8084
              containerPort: 8084
              protocol: TCP
            - name: tcp-8883
              containerPort: 8883
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
