apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.8.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          preferredNodePortAddressType: InternalDNS
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      # min.insync.replicas 最小同步副本数, 应小于或等于建立 Topic 时的副本数
      # 生产环境应设置大于等于 2
      min.insync.replicas: 1
      # 日志默认保存时间
      #log.retention.hours: 720
      inter.broker.protocol.version: "2.8"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kafka
                    operator: In
                    values:
                      - 'true'
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      strimzi.io/name: kafka-kafka
                  topologyKey: kubernetes.io/hostname
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kafka
                    operator: In
                    values:
                      - 'true'
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      strimzi.io/name: kafka-zookeeper
                  topologyKey: kubernetes.io/hostname
  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: kafka
                      operator: In
                      values:
                        - 'true'
                weight: 1
    topicOperator: {}
    userOperator: {}
