apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  ports:
    - name: zookeeper-2181
      port: 2181
    - name: zookeeper-2888
      port: 2888
    - name: zookeeper-3888
      port: 3888
    - name: kafka
      port: 9092
    - name: internal
      port: 9093
    - name: external
      port: 9094
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: kafka
                topologyKey: kubernetes.io/hostname
      containers:
        - name: kafka
          image: /kafka:2.8.1
          resources:
            requests:
              cpu: 50m
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
          ports:
            - name: zookeeper-2181
              containerPort: 2181
            - name: zookeeper-2888
              containerPort: 2888
            - name: zookeeper-3888
              containerPort: 3888
            - name: kafka
              containerPort: 9092
            - name: internal
              containerPort: 9093
            - name: external
              containerPort: 9094
          env:
            - name: REPLICAS
              value: '1'
          volumeMounts:
            - name: kafka
              mountPath: /tmp
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: kafka
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem