apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-minio-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: nfsv4
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 39000
  selector:
    app: minio
  type: NodePort
  internalTrafficPolicy: Cluster
---
kind: Service
apiVersion: v1
metadata:
  name: minio-console
  labels:
    app: minio
spec:
  ports:
    - name: http
      port: 9001
      targetPort: 9001
  selector:
    app: minio
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster
---
kind: Secret
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
data:
  rootPassword: Z2VvdmlzQDEyMw==
  rootUser: YWRtaW4=
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: '/minio:RELEASE.2022-03-17T06-34-49Z'
          command:
            - /bin/sh
            - '-ce'
            - >-
              /usr/bin/docker-entrypoint.sh minio server /export 
              --address :9000 --console-address :9001
          ports:
            - name: http
              containerPort: 9000
            - name: http-console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootPassword
            - name: ENDPOINT
              value: minio
          volumeMounts:
            - name: minio
              mountPath: /export
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio-minio-0
