apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - name: mongo
      port: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        middleware: 'true'
      containers:
        - name: mongo
          image: /mongo:4.4.13
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 4000m
              memory: 8Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          command:
            - mongod
            - "--replSet"
            - rs
            - "--bind_ip"
            - 0.0.0.0
#            - --clusterAuthMode
#            - keyFile
#            - --keyFile
#            - /data/mongo-keyfile
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 123456
            - name: MONGO_INITDB_DATABASE
              value: template
          volumeMounts:
            - name: mongo
              mountPath: /data/db
          imagePullPolicy: Always
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mongo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem