kind: Service
apiVersion: v1
metadata:
  name: mysql-nodeport
  namespace: ismart
  labels:
    app: mysql
  annotations:
    kubesphere.io/description: MySQL外部访问端口
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 33306
  selector:
    app: mysql
  type: NodePort