apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
data:
  POSTGRES_PASSWORD: Z2VvdmlzQDEyMw==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  PGDATA: /var/lib/postgres/data/pgdata
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: /postgres:15-alpine
          args:
            - '-c'
            - max_connections=2000
            - '-c'
            - listen_addresses=*
          ports:
            - name: postgres
              protocol: TCP
              containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 500Mi
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            tcpSocket:
              port: 5432
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 5432
          env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: PGDATA
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgres/data
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem