apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: predixy
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: predixy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: predixy
data:
  predixy.conf: |
    Name Predixy-DefaultNS
    Bind 0.0.0.0:6379
    WorkerThreads 4
    ClientTimeout 0
    Include auth.conf
    ClusterServerPool {
      MasterReadPriority 10
      StaticSlaveReadPriority 50
      DynamicSlaveReadPriority 50
      RefreshInterval 1
      ServerTimeout 1
      ServerFailureLimit 10
      ServerRetryTimeout 1
      KeepAlive 120
      Servers {
        + redis-headless:6379
       }
     }
  auth.conf: |
    Authority {
      Auth {
        Mode read
      }
      Auth 123456 {
        Mode admin
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predixy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predixy
  template:
    metadata:
      labels:
        app: predixy
    spec:
      initContainers:
        - name: init
          image: '/predixy:1.0.5'
          command:
            - sh
            - '-c'
          args:
            - >-
              while [ "$(redis-cli -h redis-headless -c cluster info | grep
              state | awk -F ':' '{print $2}' | md5sum | awk '{print $1}')" !=
              "d3accd33402becc720abebee93ebe193" ]; do echo "Waiting for redis
              initialization complete..."; sleep 10; done; echo "redis has
              initialized...";
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: predixy
                topologyKey: kubernetes.io/hostname
      containers:
        - name: predixy
          image: /predixy:1.0.5
          command:
            - /usr/bin/predixy
            - /etc/predixy/predixy.conf
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /etc/predixy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: predixy
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: predixy
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageValue":"4Mi"}}]'
    cpuTargetUtilization: "80"
    memoryTargetValue: 4Mi
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: predixy
  targetCPUUtilizationPercentage: 80
