apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  clusterIP: None
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
data:
  advanced.config: |
    [
      {rabbitmq_auth_backend_ldap, [
        %% Authorisation
      ]}
    ].
  enabled_plugins: |
    [
      rabbitmq_management
    ].
  rabbitmq.conf: |
    loopback_users.guest = false
    default_user = admin
    default_pass = 123456
    ## Number of Erlang processes that will accept connections for the TCP
    ## and TLS listeners.
    ##
    # num_acceptors.tcp = 10
    # num_acceptors.ssl = 10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: /rabbitmq:3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_NODE_PORT
              value: '5672'
          volumeMounts:
            - name: rabbitmq
              mountPath: /var/lib/rabbitmq/mnesia
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq
            defaultMode: 420
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: rabbitmq
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        volumeMode: Filesystem