apiVersion: v1
kind: Service
metadata:
  name: xxl
  labels:
    app: xxl
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 任务调度中心
spec:
  ports:
    - name: xxl
      port: 8080
  clusterIP: None
  selector:
    app: xxl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xxl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxl
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 任务调度中心
data:
  param: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl
  labels:
    app: xxl
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 任务调度中心
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl
  template:
    metadata:
      labels:
        app: xxl
    spec:
      nodeSelector:
        microsvc: 'true'
      containers:
        - name: xxl
          image: /xxl-job-admin:2.3.0
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: xxl
              containerPort: 8080
          env:
            - name: PARAMS
              valueFrom:
                configMapKeyRef:
                  name: xxl
                  key: param
          volumeMounts:
            - name: xxl
              mountPath: /data/applogs
      volumes:
        - name: xxl
          persistentVolumeClaim:
            claimName: xxl
