apiVersion: v1
kind: Namespace
metadata:
  name: tidb-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tidb-controller-manager
  namespace: tidb-operator
  labels:
    app.kubernetes.io/name: tidb-controller-manager
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-controller-manager
  labels:
    app.kubernetes.io/name: tidb-controller-manager
rules:
  - apiGroups: [""]
    resources:
      - services
      - events
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["endpoints","configmaps"]
    verbs: ["create", "get", "list", "watch", "update","delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create","get","update","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "list", "watch","delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch","update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets","deployments", "controllerrevisions"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["apps.pingcap.com"]
    resources: ["statefulsets", "statefulsets/status"]
    verbs: ["*"]
  - apiGroups: ["pingcap.com"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch", "update", "create"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [clusterroles,roles]
    verbs: ["escalate","create","get","update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings","clusterrolebindings"]
    verbs: ["create","get","update", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-controller-manager
  labels:
    app.kubernetes.io/name: tidb-controller-manager
subjects:
  - kind: ServiceAccount
    name: tidb-controller-manager
    namespace: tidb-operator
roleRef:
  kind: ClusterRole
  name: tidb-controller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-controller-manager
  namespace: tidb-operator
  labels:
    app.kubernetes.io/name: tidb-controller-manager
rules:
  - apiGroups: [""]
    resources:
      - services
      - events
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["endpoints","configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create","get","update","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch","update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets","deployments", "controllerrevisions"]
    verbs: ["*"]
  - apiGroups: ["apps.pingcap.com"]
    resources: ["statefulsets", "statefulsets/status"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["pingcap.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["escalate","create","get","update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create","get","update", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-controller-manager
  namespace: tidb-operator
  labels:
    app.kubernetes.io/name: tidb-controller-manager
subjects:
  - kind: ServiceAccount
    name: tidb-controller-manager
roleRef:
  kind: Role
  name: tidb-controller-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tidb-controller-manager
  namespace: tidb-operator
  labels:
    app.kubernetes.io/name: tidb-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tidb-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tidb-controller-manager
    spec:
      serviceAccountName: tidb-controller-manager
      containers:
      - name: tidb-operator
        image: /tidb-operator:v1.4.4
        livenessProbe:
          tcpSocket:
            port: 6060
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        command:
          - /usr/local/bin/tidb-controller-manager
          - -tidb-backup-manager-image=/tidb-backup-manager:v1.4.4
          - -tidb-discovery-image=/tidb-operator:v1.4.4
          - -cluster-scoped=true
          - -cluster-permission-node=true
          - -cluster-permission-pv=true
          - -cluster-permission-sc=true
          - -auto-failover=true
          - -pd-failover-period=5m
          - -tikv-failover-period=5m
          - -tiflash-failover-period=5m
          - -tidb-failover-period=5m
          - -dm-master-failover-period=5m
          - -dm-worker-failover-period=5m
          - -detect-node-failure=false
#          - -pod-hard-recovery-period=24h
          - -v=2
          - -features=AdvancedStatefulSet=false,StableScheduling=true,AutoScaling=true,VolumeModifying=true
          - -workers=5
          - -leader-lease-duration=15s
          - -leader-renew-deadline=10s
          - -leader-retry-period=2s
          - -kube-client-qps=5
          - -kube-client-burst=10
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: Asia/Shanghai
      nodeSelector: {}
      affinity: {}
      tolerations: []
      securityContext: {}
