apiVersion: v1
kind: Service
metadata:
  name: chrome
  labels:
    app: chrome
spec:
  type: NodePort
  ports:
    - name: chrome
      port: 6901
      nodePort: 33001
  selector:
    app: chrome
---
apiVersion: v1
kind: Secret
metadata:
  name: chrome
data:
  VNC_USER: YWRtaW4=
  VNC_PW: Z2VvdmlzQDEyMw==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  labels:
    app: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
        - name: chrome
          image: /chrome:1.13.0
          ports:
            - name: chrome
              containerPort: 6901
          env:
            - name: VNC_USER
              valueFrom:
                secretKeyRef:
                  name: chrome
                  key: VNC_USER
            - name: VNC_PW
              valueFrom:
                secretKeyRef:
                  name: chrome
                  key: VNC_PW
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi