kind: Service
apiVersion: v1
metadata:
  name: dbeaver
  labels:
    app: dbeaver
spec:
  ports:
    - name: dbeaver
      protocol: TCP
      port: 8978
      targetPort: 8978
      nodePort: 38978
  selector:
    app: dbeaver
  type: NodePort
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: dbeaver
  labels:
    app: dbeaver
spec:
  serviceName: dbeaver
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      containers:
        - name: dbeaver
          image: '/cloudbeaver:23.0.5'
          ports:
            - name: dbeaver
              containerPort: 8978
              protocol: TCP
          volumeMounts:
            - name: dbeaver
              mountPath: /opt/cloudbeaver/workspace
          livenessProbe:
            httpGet:
              path: /
              port: 8978
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8978
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: dbeaver
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
