apiVersion: v1
kind: Service
metadata:
  name: kafka-map
  labels:
    app: kafka-map
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  type: NodePort
  ports:
    - name: kafka-map
      port: 8080
      nodePort: 38079
  selector:
    app: kafka-map
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-map
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-map
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
data:
  DEFAULT_USERNAME: admin
  DEFAULT_PASSWORD: 123456
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-map
  labels:
    app: kafka-map
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 消息队列
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-map
  template:
    metadata:
      labels:
        app: kafka-map
    spec:
      initContainers:
        - name: init-kafka
          image: /busybox:1.35.0
          command: ['sh', '-c']
          args:
            - echo "Prepare to Kafka initializing...";
              until nc -w 1 -z kafka 9092;
              do echo "Waiting for Kafka initialization complete..."; sleep 10; done;
              echo "Kafka has initialized...";
      containers:
        - name: kafka-map
          image: /kafka-map:1.3.1
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: kafka-map
              containerPort: 8080
          env:
            - name: DEFAULT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-map
                  key: DEFAULT_USERNAME
            - name: DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kafka-map
                  key: DEFAULT_PASSWORD
          volumeMounts:
            - name: kafka-map
              mountPath: /usr/local/kafka-map/data
      volumes:
        - name: kafka-map
          persistentVolumeClaim:
            claimName: kafka-map