apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
    app.kubernetes.io/name: nexus
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: maven 私服
spec:
  type: NodePort
  ports:
    - name: nexus
      port: 8081
      nodePort: 38078
  selector:
    app: nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: 搜索引擎服务
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: /nexus:3.38.1
          resources:
            requests:
              cpu: 4
              memory: 512Mi
            limits:
              cpu: 8
              memory: 8Gi
          ports:
            - containerPort: 8081
              name: nexus
          volumeMounts:
            - name: nexus
              mountPath: /nexus-data
      volumes:
        - name: nexus
          persistentVolumeClaim:
            claimName: nexus