apiVersion: v1
kind: Service
metadata:
  name: redisinsight
spec:
  ports:
    - port: 80
      targetPort: 30002
  selector:
    app: redisinsight
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      initContainers:
        - name: init
          image: /busybox:1.35.0
          command:
            - /bin/sh
            - '-c'
            - |
              chown -R 1001 /db
          volumeMounts:
            - name: redisinsight
              mountPath: /db
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name:  redisinsight
          image: /redisinsight:1.14.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: redisinsight
              mountPath: /db
          ports:
            - containerPort: 8001
              protocol: TCP
      volumes:
        - name: redisinsight
          persistentVolumeClaim:
            claimName: redisinsight
